import Head from 'next/head'

import { Inter } from 'next/font/google'
import { useState, useEffect, SetStateAction } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [darkTheme, setDarkTheme] = useState(undefined)

  const handleToggle = (e: { target: { checked: SetStateAction<any> } }) => {
    setDarkTheme(e.target.checked)
  }

  useEffect(() => {
    if (darkTheme !== undefined) {
      if (darkTheme) {
        document.querySelector('html')?.setAttribute('data-theme', 'dark')
        window.localStorage.setItem('theme', 'dark')
      } else {
        document.querySelector('html')?.removeAttribute('data-theme')
        window.localStorage.setItem('theme', 'light')
      }
    }
  }, [darkTheme])

  useEffect(() => {
    const root = window.document.documentElement;
    const initialColorValue = root.style.getPropertyValue(
      '--initial-color-mode'
    );
    // Set initial darkmode to light
    setDarkTheme(initialColorValue === 'dark')
  }, []);


  const favicon = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><text y="50%" font-size="90" text-anchor="middle">${encodeURIComponent(
    '💻'
  )}</text></svg>`
  return (
    <>
      <Head>
        <title>Ihsan Hepsen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link rel="icon" type="image/svg+xml" href={favicon} />
      </Head>
      <div className='container'>
        <nav>
          <div className='mybrand'>
            Ihsan Hepsen
          </div>
          <div>
            <form action="#">
              <label className="switch">
                <input type="checkbox" checked={darkTheme} onChange={(e) => handleToggle(e)} />
                <span className="slider"></span>
              </label>
            </form>
          </div>
        </nav>
        <section>
          <div className="heroSection">
            <h1>👋 Hi Ihsan here</h1>
            <h3>
              I'm a full-stack software engineer and web developer.
            </h3>
            <p>
              As a full-stack software engineer and web developer, I have extensive experience working with various technologies,
              including Java Spring, React.js, and TypeScript. I have built several web applications using these technologies,
              and I'm comfortable working on both the front-end and back-end parts of the stack.
              <br />
              <br />
              In addition to deploying applications to cloud services like Google App Engine and Azure, I have also
              built microservices using containerization technologies like Docker, ensuring the
              scalability and maintainability of the services.
            </p>
            <button className='primary-btn'>
              Connect on LinkedIn
            </button>
          </div>
        </section>
      </div>
    </>
  )
}
