import Head from 'next/head'

import { useState, useEffect, SetStateAction } from 'react'
import { Catamaran } from 'next/font/google'

import { Avatar } from '@mui/material'
import {
  LightMode as LightModeIcon,
  DarkMode
} from '@mui/icons-material'
import ButtonGroupNav from '@/components/ButtonGroupNav'
import ProjectSection from '@/components/static/ProjectsSection'
import AboutSection from '@/components/static/AboutSection'
import SkillsSection from '@/components/static/SkillsSection'
import SocialsSection from '@/components/static/SocialsSection'


const inter = Catamaran({ subsets: ['latin'] })

export default function Home() {

  const [darkTheme, setDarkTheme] = useState(undefined)

  const handleToggle = (e: { target: { checked: SetStateAction<any> } }) => {
    setDarkTheme(e.target.checked)
  }

  useEffect(() => {
    if (darkTheme !== undefined) {
      if (darkTheme) {
        document.querySelector('html')?.setAttribute('data-theme', 'dark')
        window.localStorage.setItem('theme', 'dark')
      } else {
        document.querySelector('html')?.removeAttribute('data-theme')
        window.localStorage.setItem('theme', 'light')
      }
    }
  }, [darkTheme])

  useEffect(() => {
    const root = window.document.documentElement;
    const initialColorValue = root.style.getPropertyValue(
      '--initial-color-mode'
    );
    // Set initial darkmode to light
    // @ts-ignore
    setDarkTheme(initialColorValue === 'dark')
  }, []);


  const favicon = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><text y="50%" font-size="90" text-anchor="middle">${encodeURIComponent(
    '💻'
  )}</text></svg>`

  return (
    <>
      <Head>
        <title>Ihsan Hepsen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg+xml" href={favicon} />
      </Head>

      <div className='container'>
        <nav>
          <Avatar alt="Ihsan Hepsen profile pic" src="/profile-pic.jpg" sx={{ width: 140, height: 140 }} />
          <div className="toggle-container">
            <LightModeIcon />
            <label className="switch">
              <input type="checkbox" checked={darkTheme} onChange={(e) => handleToggle(e)} />
              <span className="slider"></span>
            </label>
            <DarkMode />
          </div>
        </nav>

        <ButtonGroupNav />
        <AboutSection />
        <SkillsSection />
        <ProjectSection />
        <SocialsSection />
      </div>
    </>
  )
}
